SWEP.PrintName = "Generic Example"
SWEP.Category = "sk's example weapons"
SWEP.Spawnable = true
SWEP.Base = "skb_generic"
SWEP.SKB_ShootSound = Sound("Weapon_SMG1.Single")
SWEP.Primary.Damage = 8
SWEP.Primary.ClipSize = 32
SWEP.Primary.Ammo = "smg1"
SWEP.Primary.DefaultClip = 32
SWEP.Primary.Spread = 0
SWEP.Primary.Automatic = true
SWEP.Primary.Delay = 0.07
SWEP.Force = 1.1
SWEP.SKB_VX = -4.0
SWEP.SKB_VY = 2.0
SWEP.SKB_VZ = 10.0
SWEP.Slot = 1
SWEP.SlotPos = 1
SWEP.ViewModel = "models/weapons/c_smg1.mdl"
SWEP.WorldModel = "models/weapons/w_smg1.mdl"
SWEP.HoldType = "smg"
SWEP.SKB_RecoilX = 67.5
SWEP.SKB_RecoilY = 59
