SWEP.PrintName = "Sniper Example"
SWEP.Category = "sk's example weapons"
SWEP.Spawnable = true
SWEP.Base = "skb_sniper"
SWEP.SKB_ShootSound = Sound("Weapon_357.Single")
SWEP.Primary.Damage = 100
SWEP.Primary.ClipSize = 5
SWEP.Primary.Ammo = "357"
SWEP.Primary.DefaultClip = 5
SWEP.Primary.Spread = 1.5
SWEP.Primary.Automatic = true
SWEP.Primary.Delay = 1.4
SWEP.Force = 1
SWEP.SKB_VX = 42.0
SWEP.SKB_VY = 6.0
SWEP.SKB_VZ = 18.0
SWEP.Slot = 1
SWEP.SlotPos = 1
SWEP.ViewModel = "models/weapons/c_357.mdl"
SWEP.WorldModel = "models/weapons/w_357.mdl"
SWEP.HoldType = "ar2"
SWEP.SKB_RecoilX = 73.25
SWEP.SKB_RecoilY = 69.5